name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_DOCKER_REDMINE_DEPLOY_USER }}
        password: ${{ secrets.DOCKERHUB_DOCKER_REDMINE_DEPLOY_KEY}}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag yaeremin/docker-redmine:latest && docker push yaeremin/docker-redmine:latest
